### ISSUE TITLE
error in eclipse

### ISSUE THREAD

**Issue by Jesan** [OneSourceConsult/floodlight-queuepusher#2]
Hi 

When i loaded your module , it shows a comilation error for this line 

measure("createQueue", (String)args.get("switchid"));

Please tell me how to solve this error , am i missing any dependencies ? 

Regards
Jesan

**Comment by dfpalma** [comment]
Hi again,

We need more details to try to understand what the problem is. What was error that you got?

**Comment by Jesan** [comment]
hi 
 It shows the compilation error in eclipse when i build and run in that line . It shows measure function is undefined...

Regards,
Jesan

**Comment by joagoncaonesource** [comment]
Hi,

That is our mistake. When we uploaded this piece of code, we mistakenly left references for our other tool (https://github.com/OneSourceConsult/JavaProfiling-tool). I will remove those references and push the changes.

Either way, for now you can just comment out every call to "measure" and the package import on top.

Best,
João

**Comment by Jesan** [comment]
Thanks after commenting that measure I didn't get any errors wen complied 

Regards 
Jesanraj
